test<- read.csv("~/Downloads/test.csv")
train<- read.csv("~/Downloads/train.csv")

#find na in test/train
tag_train_na<-subset(train, is.na(train$tag_type))
tag_test_na<-subset(test, is.na(test$tag_type))
train$tag_type<-as.character(train$tag_type)
test$tag_type<-as.character(test$tag_type)
#clean tag in train
train$tag_type<-as.character(train$tag_type)
train$tag_type[train$summary=="bench/Bench"]<-'bench'
train$tag_type[train$summary=="Survey/survey"]<-'survey'
train$tag_type[train$summary=="graffiti/cars in yard/Graffiti/Other:Signs"]<-'graffiti'
train$tag_type[train$summary=="pothole/hole/potholes/Potholes/Pothole/POTHOLE"]<-'pothole'
train$tag_type[train$summary=="Other"]<-'drug_dealing'
train$tag_type[train$summary=="Drainage/Flooding/drainage"]<-'drain_problem'
train$tag_type[train$summary=="Garbage/Dumpling/dump/Dump/dumpling/trash/Trash/furniture/matress"]<-'trash'
train$tag_type[train$summary=="lights/Deterioration/light/Light/traffic/Traffic/signal/Signals/Signal/signals"]<-'street_light'
train$tag_type[train$summary=="limb/Ave/tree/Tree/Debris/debris"]<-'tree'
train$tag_type[train$summary=="complaint/Complaint/Complaints/complaints"]<-'complaint'
train$tag_type[train$summary=="violation/Violation"]<-'violation'
train$tag_type[train$summary=="Survey/survey"]<-'survey'
train$tag_type[train$summary=="maintenance/park/Park"]<-'maintenance'
train$tag_type[train$summary=="sign/signs/Sign/Signs"]<-'signs'
train$tag_type[train$summary=="signal/Signals/Signal/signals"]<-'street_sign'
train$tag_type[train$summary=="snow/Snow"]<-'snow'
train$tag_type[train$summary=="traffic/Traffic"]<-'traffic'
train$tag_type[train$summary=="zone/zoning/Zone"]<-'zoning'
train$tag_type[train$summary=="Abandoned Vehicle/vehicle"]<-'abandoned_vehicle'
train$tag_type[train$summary=="driving/Drive/drive/driving"]<-'bad_driving'
train$tag_type[train$summary=="bench/Bench"]<-'bench'
train$tag_type[train$summary=="bike/bicycle/Bike"]<-'bike_concern'
train$tag_type[train$summary=="property/brush"]<-'blighted_property'
train$tag_type[train$summary=="walk/cross"]<-'crosswalk'
train$tag_type[train$summary=="Other"]<-'drug_dealing'
train$tag_type[train$summary=="hydrant/water"]<-'hydrant'
train$tag_type[train$summary=="hot/heat/Heat"]<-'heat'
train$tag_type[train$summary=="homeless/no home"]<-'homeless'
train$tag_type[train$summary=="idle/idling"]<-'illegal_idling'
train$tag_type[train$summary=="graffiti/cars in yard/Graffiti"]<-'graffiti'
train$tag_type[train$summary=="parked/parking/van/car"]<-'parking_meter'
train$tag_type[train$summary=="lights/Deterioration/light/Light"]<-'street_light'
train$tag_type[train$summary=="limb/Ave/tree/Tree/Debris/debris"]<-'tree'
train$tag_type[train$summary=="sewer/sewage/porch/Other"]<-'sidewalk'
train$tag_type[train$summary=="pothole/hole/potholes/Potholes/Pothole/POTHOLE"]<-'pothole'
train$tag_type[train$summary=="Abandoned/couch/pick ups/Grace/items/leaves/spring/discarded/damaged/abandoned/trash
               /dumping/dumped/Dumping/Dump/bulk/BULK/Bulkdiscarded/furniture/matress/waste"]<-'trash'
train$tag_type[train$summary=="Other/employees/debri/dresser"]<-'others'
train$tag_type[train$summary=="dog/cat/animal"]<-'animal_problem'
train$tag_type[train$summary=="maintenance"]<-'maintenance'
train$tag_type[train$summary=="online"]<-'online'
train$tag_type[train$summary=="bridge"]<-'bridge'
train$tag_type[train$summary=="landlords"]<-'landlords'
train$tag_type[train$summary=="raililngs/rail"]<-'rail'
train$tag_type[train$summary=="stabbing/rob/robbery/stab"]<-'robbery'
train$tag_type[train$summary=="squatter"]<-'squatter'
train$tag_type[train$summary=="violation/Violation"]<-'violation'
train$tag_type[train$summary=="lost"]<-'lost and found'
train$tag_type[train$summary=="complaint/Complaint/Complaints/complaints"]<'noise_complaint'
train$tag_type[train$summary=="Survey/survey"]<-'survey'
train$tag_type[train$summary=="overgrowth"]<-'overgrothw'
train$tag_type[train$summary=="pedestrian"]<-'pedestrian_light'
train$tag_type[train$summary=="prostitude/prostitution"]<-'prostitution'
train$tag_type[train$summary=="art"]<-'public_art'
train$tag_type[train$summary=="concern"]<-'public_concern'
train$tag_type[train$summary=="road/safe/safety"]<-'road_safety'
train$tag_type[train$summary=="crash/kill/accident"]<-'roadkill'
train$tag_type[train$summary=="rodent/rodents"]<-'rodents'
train$tag_type[train$summary=="Drain/drain/Drainage/Flooding/drainage/flooding"]<-'drain_problem'
train$tag_type[is.na(train$tag_type)]<-'unknown'


#clean NA in test$tag_type
test$tag_type[test$summary=="bench/Bench"]<-'bench'
test$tag_type[test$summary=="Survey/survey"]<-'survey'
test$tag_type[test$summary=="graffiti/cars in yard/Graffiti/Other:Signs"]<-'graffiti'
test$tag_type[test$summary=="pothole/hole/potholes/Potholes/Pothole/POTHOLE"]<-'pothole'
test$tag_type[test$summary=="Other"]<-'drug_dealing'
test$tag_type[test$summary=="Drainage/Flooding/drainage"]<-'drain_problem'
test$tag_type[test$summary=="Garbage/Dumpling/dump/Dump/dumpling/trash/Trash/furniture/matress"]<-'trash'
test$tag_type[test$summary=="lights/Deterioration/light/Light/traffic/Traffic/signal/Signals/Signal/signals"]<-'street_light'
test$tag_type[test$summary=="limb/Ave/tree/Tree/Debris/debris"]<-'tree'
test$tag_type[test$summary=="complaint/Complaint/Complaints/complaints"]<-'complaint'
test$tag_type[test$summary=="violation/Violation"]<-'violation'
test$tag_type[test$summary=="Survey/survey"]<-'survey'
test$tag_type[test$summary=="maintenance/park/Park"]<-'maintenance'
test$tag_type[test$summary=="sign/signs/Sign/Signs"]<-'signs'
test$tag_type[test$summary=="signal/Signals/Signal/signals"]<-'street_sign'
test$tag_type[test$summary=="snow/Snow"]<-'snow'
test$tag_type[test$summary=="traffic/Traffic"]<-'traffic'
test$tag_type[test$summary=="zone/zoning/Zone"]<-'zoning'
test$tag_type[test$summary=="Abandoned Vehicle/vehicle"]<-'abandoned_vehicle'
test$tag_type[test$summary=="driving/Drive/drive/driving"]<-'bad_driving'
test$tag_type[test$summary=="bench/Bench"]<-'bench'
test$tag_type[test$summary=="bike/bicycle/Bike"]<-'bike_concern'
test$tag_type[test$summary=="property/brush"]<-'blighted_property'
test$tag_type[test$summary=="walk/cross"]<-'crosswalk'
test$tag_type[test$summary=="Other"]<-'drug_dealing'
test$tag_type[test$summary=="hydrant/water"]<-'hydrant'
test$tag_type[test$summary=="hot/heat/Heat"]<-'heat'
test$tag_type[test$summary=="homeless/no home"]<-'homeless'
test$tag_type[test$summary=="idle/idling"]<-'illegal_idling'
test$tag_type[test$summary=="graffiti/cars in yard/Graffiti"]<-'graffiti'
test$tag_type[test$summary=="parked/parking/van/car"]<-'parking_meter'
test$tag_type[test$summary=="lights/Deterioration/light/Light"]<-'street_light'
test$tag_type[test$summary=="limb/Ave/tree/Tree/Debris/debris"]<-'tree'
test$tag_type[test$summary=="sewer/sewage/porch/Other"]<-'sidewalk'
test$tag_type[test$summary=="pothole/hole/potholes/Potholes/Pothole/POTHOLE"]<-'pothole'
test$tag_type[test$summary=="Abandoned/couch/pick ups/Grace/items/leaves/spring/discarded/damaged/abandoned/trash
              /dumping/dumped/Dumping/Dump/bulk/BULK/Bulkdiscarded/furniture/matress/waste"]<-'trash'
test$tag_type[test$summary=="Other/employees/debri/dresser"]<-'others'
test$tag_type[test$summary=="dog/cat/animal"]<-'animal_problem'
test$tag_type[test$summary=="maintenance"]<-'maintenance'
test$tag_type[test$summary=="online"]<-'online'
test$tag_type[test$summary=="bridge"]<-'bridge'
test$tag_type[test$summary=="landlords"]<-'landlords'
test$tag_type[test$summary=="raililngs/rail"]<-'rail'
test$tag_type[test$summary=="stabbing/rob/robbery/stab"]<-'robbery'
test$tag_type[test$summary=="squatter"]<-'squatter'
test$tag_type[test$summary=="violation/Violation"]<-'violation'
test$tag_type[test$summary=="lost"]<-'lost and found'
test$tag_type[test$summary=="complaint/Complaint/Complaints/complaints"]<'noise_complaint'
test$tag_type[test$summary=="Survey/survey"]<-'survey'
test$tag_type[test$summary=="overgrowth"]<-'overgrothw'
test$tag_type[test$summary=="pedestrian"]<-'pedestrian_light'
test$tag_type[test$summary=="prostitude/prostitution"]<-'prostitution'
test$tag_type[test$summary=="art"]<-'public_art'
test$tag_type[test$summary=="concern"]<-'public_concern'
test$tag_type[test$summary=="road/safe/safety"]<-'road_safety'
test$tag_type[test$summary=="crash/kill/accident"]<-'roadkill'
test$tag_type[test$summary=="rodent/rodents"]<-'rodents'
test$tag_type[test$summary=="Drain/drain/Drainage/Flooding/drainage/flooding"]<-'drain_problem'
test$tag_type[is.na(test$tag_type)]<-'unknown'
test$tag_type[test$tag_type=="bus_lane"]<-'unknown'
#check if exists NA
tag_test_na2<-subset(test, is.na(test$tag_type))
tag_train_na2<-subset(train, is.na(train$tag_type))

